name: githubAction
on: [workflow_dispatch]
jobs:
  MyJobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependensies
        run: npm ci
      - name: Run Test
        run: npm test
